export const BUILTIN_TRICKS = [
  {
    id: "scholars-mate",
    name: "Scholar's Mate",
    opening: "Open Game",
    side: "White",
    difficulty: "Easy",
    tags: ["Checkmate", "f7 Attack", "Four-Move Mate"],
    description: "The classic four-move checkmate targeting the weak f7 square (protected only by the Black King). While common against beginners, it is highly risky against players who know how to defend it.",
    moves: [
      { move: "e2-e4", san: "e4", comment: "White claims space in the center and opens lines for the Queen and light-squared Bishop." },
      { move: "e7-e5", san: "e5", comment: "Black responds symmetrically, occupying the center." },
      { move: "d1-h5", san: "Qh5", comment: "The White Queen ventures out early, applying pressure on e5 and staring at f7." },
      { move: "b8-c6", san: "Nc6", comment: "Black develops the knight to defend the threatened e5 pawn." },
      { move: "f1-c4", san: "Bc4", comment: "White coordinates a second attack on f7. White is now threatening checkmate on the next move!" },
      { move: "g8-f6", san: "Nf6", comment: "Black develops the knight and attacks the Queen, but completely misses the checkmate threat!" },
      { move: "h5-f7", san: "Qxf7#", comment: "Checkmate! The Queen captures on f7, supported by the bishop. The King is trapped." }
    ]
  },
  {
    id: "legals-trap",
    name: "Légal's Trap",
    opening: "Philidor Defense",
    side: "White",
    difficulty: "Medium",
    tags: ["Queen Sacrifice", "Active Play", "Smothered Mate"],
    description: "Named after Sire de Légal, this trap involves an incredible temporary Queen sacrifice to deliver a spectacular checkmate with two Knights and a Bishop.",
    moves: [
      { move: "e2-e4", san: "e4", comment: "Standard center opening." },
      { move: "e7-e5", san: "e5", comment: "Black responds symmetrically." },
      { move: "g1-f3", san: "Nf3", comment: "White attacks e5 and develops the knight." },
      { move: "d7-d6", san: "d6", comment: "Black opts for the Philidor Defense, securing the center but locking in the dark-squared bishop." },
      { move: "b1-c3", san: "Nc3", comment: "White develops the second knight toward the center." },
      { move: "c8-g4", san: "Bg4", comment: "Black pins the f3-knight to the Queen, a very common pinning theme." },
      { move: "f1-c4", san: "Bc4", comment: "White develops the bishop, aiming at the f7 square and preparing the trap." },
      { move: "h7-h6", san: "h6", comment: "Black plays a passive pawn move, hoping to prevent any knight leaps." },
      { move: "f3-e5", san: "Nxe5!", comment: "The shocking Queen Sacrifice! White ignores the pin and takes the e5 pawn, attacking Black's bishop." },
      { move: "g4-d1", san: "Bxd1??", comment: "Black greedily takes the White Queen on d1, falling directly into the mate." },
      { move: "c4-f7", san: "Bxf7+", comment: "Check! The Bishop strikes f7, drawing the King forward to e7." },
      { move: "e8-e7", san: "Ke7", comment: "The only legal square for the Black King." },
      { move: "c3-d5", san: "Nd5#", comment: "Checkmate! The knights and bishop create a perfect cage. A historic mating net!" }
    ]
  },
  {
    id: "blackburne-shilling",
    name: "Blackburne Shilling Gambit",
    opening: "Italian Game",
    side: "Black",
    difficulty: "Medium",
    tags: ["Gambit", "Royal Fork", "Smothered Mate"],
    description: "An infamous trap where Black offers a free pawn on e5. If White accepts and plays greedily, Black launches a devastating double-attack with the Queen leading to a smothered mate.",
    moves: [
      { move: "e2-e4", san: "e4", comment: "White opens with the King's pawn." },
      { move: "e7-e5", san: "e5", comment: "Black matches it." },
      { move: "g1-f3", san: "Nf3", comment: "White attacks e5." },
      { move: "b8-c6", san: "Nc6", comment: "Black defends." },
      { move: "f1-c4", san: "Bc4", comment: "White develops the Italian bishop, targeting f7." },
      { move: "c6-d4", san: "Nd4!?", comment: "The Blackburne Shilling Gambit! Black leaves the e5 pawn undefended, tempting White's knight." },
      { move: "f3-e5", san: "Nxe5?", comment: "White takes the bait, expecting to threaten a fork on f7, but falls into the trap." },
      { move: "d8-g5", san: "Qg5!", comment: "A powerful double attack! The Black Queen attacks the e5 Knight and the g2 pawn." },
      { move: "e5-f7", san: "Nxf7?!", comment: "White forks the Rook and Queen, thinking they are winning material." },
      { move: "g5-g2", san: "Qxg2!", comment: "Black ignores the fork and strikes g2, threatening the h1 rook and putting White on the run." },
      { move: "h1-f1", san: "Rf1", comment: "White's only move to save the rook." },
      { move: "g2-e4", san: "Qxe4+", comment: "Check! The Queen recaptures the pawn, forcing White to block." },
      { move: "c4-e2", san: "Be2", comment: "White blocks with the bishop. If White blocks with Queen, Black wins it with NxQ." },
      { move: "d4-f3", san: "Nf3#", comment: "Checkmate! The knight delivers a smothered mate. The White bishop cannot capture because it is pinned by the Queen!" }
    ]
  },
  {
    id: "fishing-pole",
    name: "Fishing Pole Trap",
    opening: "Ruy Lopez",
    side: "Black",
    difficulty: "Hard",
    tags: ["Knight Sacrifice", "Open h-file", "Unstoppable Mate"],
    description: "A counter-attacking trap in the Berlin Defense of the Ruy Lopez. Black baits White into capturing an advanced knight on g4, which opens up the h-file for an unstoppable attack by the Black Queen.",
    moves: [
      { move: "e2-e4", san: "e4", comment: "Standard open game." },
      { move: "e7-e5", san: "e5", comment: "Symmetric response." },
      { move: "g1-f3", san: "Nf3", comment: "White develops Knight." },
      { move: "b8-c6", san: "Nc6", comment: "Black develops Knight." },
      { move: "f1-b5", san: "Bb5", comment: "The Ruy Lopez (Spanish Opening)." },
      { move: "g8-f6", san: "Nf6", comment: "The Berlin Defense." },
      { move: "e1-g1", san: "O-O", comment: "White castles safely." },
      { move: "f6-g4", san: "Ng4!?", comment: "The 'Fishing Pole' begins! Black advances the knight, setting a deep trap." },
      { move: "h2-h3", san: "h3", comment: "White kicks the active knight, expecting it to retreat." },
      { move: "h7-h5", san: "h5!", comment: "The bait! Black leaves the knight en prise and opens the h-file pathway instead." },
      { move: "h3-g4", san: "hxg4?", comment: "White takes the knight, opening up a direct line to their own king." },
      { move: "h5-g4", san: "hxg4", comment: "Black recaptures, attacking White's f3 knight and opening the h-file." },
      { move: "f3-e1", san: "Ne1", comment: "White's knight retreats, leaving the f-pawn and h-file exposed." },
      { move: "d8-h4", san: "Qh4", comment: "The Queen arrives on the h-file. Checkmate on h2 or h1 is now imminent." },
      { move: "f2-f3", san: "f3", comment: "White tries to make an escape path for their King via f2." },
      { move: "g4-g3", san: "g3!", comment: "Crucial move! Black blocks the f2 square, locking the White King inside." },
      { move: "d2-d4", san: "d4", comment: "White tries to open space, but it is too late." },
      { move: "h4-h1", san: "Qh1#", comment: "Checkmate! The Queen delivers the final blow supported by the g3 pawn." }
    ]
  },
  {
    id: "stafford-gambit",
    name: "Stafford Gambit",
    opening: "Petrov Defense",
    side: "Black",
    difficulty: "Medium",
    tags: ["Gambit", "Piece Activity", "Tactical Fireworks"],
    description: "The Stafford Gambit is an extremely dangerous line for Black. In exchange for a pawn, Black gets rapid development, active diagonals for both bishops, and tricky patterns that can catch White off guard.",
    moves: [
      { move: "e2-e4", san: "e4", comment: "White plays e4." },
      { move: "e7-e5", san: "e5", comment: "Black plays e5." },
      { move: "g1-f3", san: "Nf3", comment: "White attacks e5." },
      { move: "g8-f6", san: "Nf6", comment: "Petrov's Defense." },
      { move: "f3-e5", san: "Nxe5", comment: "White takes the pawn." },
      { move: "b8-c6", san: "Nc6!?", comment: "The Stafford Gambit! Black offers to trade knights rather than defend the e5 pawn." },
      { move: "e5-c6", san: "Nxc6", comment: "White accepts the trade." },
      { move: "d7-c6", san: "dxc6", comment: "Black recaptures with the d-pawn, opening lines for both bishops and the Queen." },
      { move: "d2-d3", san: "d3", comment: "White solidifies the center." },
      { move: "f8-c5", san: "Bc5", comment: "Black develops the bishop to target the weak f2 square." },
      { move: "c1-g5", san: "Bg5?!", comment: "White pins the f6-knight, but this is a critical mistake." },
      { move: "f6-e4", san: "Nxe4!", comment: "An amazing tactical shot! Black sacrifices the Queen to force checkmate." },
      { move: "g5-d8", san: "Bxd8??", comment: "White blindly captures the Queen, walking straight into the trap." },
      { move: "c5-f2", san: "Bxf2+", comment: "Check! The bishop targets f2, forcing the King to e2." },
      { move: "e1-e2", san: "Ke2", comment: "Only legal square for the King." },
      { move: "c8-g4", san: "Bg4#", comment: "Checkmate! The light-squared bishop delivers a crushing final blow." }
    ]
  },
  {
    id: "elephant-trap",
    name: "Elephant Trap",
    opening: "Queen's Gambit Declined",
    side: "Black",
    difficulty: "Medium",
    tags: ["Counter-Trap", "Pin Break", "Material Gain"],
    description: "An elegant trap in the Orthodox defense of the Queen's Gambit Declined. Black sets a trap by appearing to leave a central pawn pinned, but breaks the pin with a Queen sacrifice that wins a minor piece.",
    moves: [
      { move: "d2-d4", san: "d4", comment: "White opens with the Queen's pawn." },
      { move: "d7-d5", san: "d5", comment: "Black responds symmetrically." },
      { move: "c2-c4", san: "c4", comment: "The Queen's Gambit, offering a flank pawn for central control." },
      { move: "e7-e6", san: "e6", comment: "Black declines the gambit, solidifying d5." },
      { move: "b1-c3", san: "Nc3", comment: "White develops a knight and attacks d5." },
      { move: "g8-f6", san: "Nf6", comment: "Black develops a knight and defends d5." },
      { move: "c1-g5", san: "Bg5", comment: "White pins the f6 knight to the Queen." },
      { move: "b8-d7", san: "Nbd7", comment: "Setting the trap. It looks like Black has misplayed, as the d5 pawn is now attacked and f6 is pinned." },
      { move: "c4-d5", san: "cxd5", comment: "White exchanges pawns, preparing to win material." },
      { move: "e6-d5", san: "exd5", comment: "Black recaptures." },
      { move: "c3-d5", san: "Nxd5?!", comment: "White grabs the 'free' pawn on d5, believing f6 is pinned. But Black plays it anyway!" },
      { move: "f6-d5", san: "Nxd5!", comment: "The trap snaps shut! Black sacrifices the Queen on d8 to win White's knight." },
      { move: "g5-d8", san: "Bxd8", comment: "White takes the Queen, thinking they are winning easily." },
      { move: "f8-b4", san: "Bb4+", comment: "Check! A crushing intermezzo. White has no king moves." },
      { move: "d1-d2", san: "Qd2", comment: "White must block with the Queen." },
      { move: "b4-d2", san: "Bxd2+", comment: "Black takes the Queen." },
      { move: "e1-d2", san: "Kxd2", comment: "White recaptures." },
      { move: "e8-d8", san: "Kxd8", comment: "Black recaptures the bishop. Black is now a full knight up!" }
    ]
  },
  {
    id: "siberian-trap",
    name: "Siberian Trap",
    opening: "Smith-Morra Gambit",
    side: "Black",
    difficulty: "Hard",
    tags: ["Gambit", "Queen Pin", "Back Rank Mate"],
    description: "A famous trap in the Smith-Morra Gambit of the Sicilian Defense. Black baits White into kicking a knight, which enables a beautiful tactical sequence that forces mate on the h2 square.",
    moves: [
      { move: "e2-e4", san: "e4", comment: "White starts with e4." },
      { move: "c7-c5", san: "c5", comment: "Black replies with the Sicilian Defense." },
      { move: "d2-d4", san: "d4", comment: "White gambits a pawn with the Morra Gambit." },
      { move: "c5-d4", san: "cxd4", comment: "Black captures." },
      { move: "c2-c3", san: "c3", comment: "White offers another pawn for rapid development." },
      { move: "d4-c3", san: "dxc3", comment: "Black accepts." },
      { move: "b1-c3", san: "Nxc3", comment: "White recaptures with the knight." },
      { move: "b8-c6", san: "Nc6", comment: "Black develops a knight." },
      { move: "g1-f3", san: "Nf3", comment: "White develops a knight." },
      { move: "e7-e6", san: "e6", comment: "Black prepares to develop the dark-squared bishop." },
      { move: "f1-c4", san: "Bc4", comment: "White develops the bishop to a strong active diagonal." },
      { move: "d8-c7", san: "Qc7", comment: "Black develops the Queen to c7, controling the e5 square and c-file." },
      { move: "e1-g1", san: "O-O", comment: "White castles." },
      { move: "g8-f6", san: "Nf6", comment: "Black develops the second knight." },
      { move: "d1-e2", san: "Qe2", comment: "White prepares to push e4-e5." },
      { move: "f6-g4", san: "Ng4", comment: "Black shifts the knight, aiming at e5 and preparing tactical threats on h2." },
      { move: "h2-h3", san: "h3?", comment: "Kicking the knight, which seems natural, but is actually a fatal blunder!" },
      { move: "c6-d4", san: "Nd4!", comment: "Sensational double attack! Black attacks the white Queen and threatens Nxf3+." },
      { move: "f3-d4", san: "Nxd4?", comment: "White captures the knight on d4, but it leaves h2 undefended." },
      { move: "c7-h2", san: "Qh2#", comment: "Checkmate! The Queen captures on h2, protected by the knight on g4." }
    ]
  },
  {
    id: "halosar-trap",
    name: "Halosar Trap",
    opening: "Blackmar-Diemer Gambit",
    side: "White",
    difficulty: "Hard",
    tags: ["Gambit", "Castling Attack", "Back Rank Mate"],
    description: "An aggressive trap in the Blackmar-Diemer Gambit. White sacrifices two central pawns to get open files, castle queenside, and unleash a double attack threatening a back-rank knight checkmate.",
    moves: [
      { move: "d2-d4", san: "d4", comment: "White starts with d4." },
      { move: "d7-d5", san: "d5", comment: "Black replies with d5." },
      { move: "e2-e4", san: "e4", comment: "The Blackmar-Diemer Gambit, offering a central pawn." },
      { move: "d5-e4", san: "dxe4", comment: "Black accepts the gambit." },
      { move: "b1-c3", san: "Nc3", comment: "White attacks e4." },
      { move: "g8-f6", san: "Nf6", comment: "Black defends e4." },
      { move: "f2-f3", san: "f3", comment: "White offers a second pawn to open files." },
      { move: "e4-f3", san: "exf3", comment: "Black accepts." },
      { move: "d1-f3", san: "Qxf3", comment: "White recaptures with the Queen, offering the d4 pawn as further bait." },
      { move: "d8-d4", san: "Qxd4", comment: "Black accepts the d4 pawn, entering the danger zone." },
      { move: "c1-e3", san: "Be3", comment: "White develops the bishop, attacking the black Queen." },
      { move: "d4-b4", san: "Qb4", comment: "Black's Queen retreats to b4, protecting b7." },
      { move: "e1-c1", san: "O-O-O", comment: "White castles queenside, instantly activating the d-file Rook." },
      { move: "c8-g4", san: "Bg4", comment: "Black pin-attacks the white Queen with the bishop." },
      { move: "c3-b5", san: "Nb5!", comment: "Astounding move! White ignores the Queen attack to threaten Nc7# checkmate." },
      { move: "g4-f3", san: "Bxf3??", comment: "Black captures the white Queen, thinking they have won the game." },
      { move: "b5-c7", san: "Nxc7#", comment: "Checkmate! The knight delivers a beautiful checkmate on c7. Black's King is completely hemmed in!" }
    ]
  }
];